### ISSUE TITLE
null vs __null__

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaq-traits#20]
Troubleshooting an issue with a `has-transformed-position` daemon with native units of `None`.  No units _should_ be allowed by the traits specification:
https://github.com/yaq-project/yaq-traits/blob/55b22dad2ff978ec6440193ce471b2e24b585ee3/yaq_traits/has-transformed-position.toml#L63-L65
but the message throws an error for me--that message type does not contain a string.  

In general, it looks like yaq-traits have null message responses in tomls specified as `"null"`, while state and config values are specified as `"__null__"`.  Should messages have `"__null__"` as the type as well?

**Comment by ksunden** [comment]
https://github.com/yaq-project/yaq-traits/blob/55b22dad2ff978ec6440193ce471b2e24b585ee3/yaq_traits/is-daemon.toml#L16-L18

Note how both forms are used here, `"null"` when specifying the type, `"__null__"` when specifying the default.

**Comment by ksunden** [comment]
As for the error you are getting, I see no reason for that to error, can you share more info?

**Comment by ddkohler** [comment]
The current problem is running the main branch of `yaqd-newport-conex-agp` and sending a `get_native_units` message.  The error message:
```
>>> c.get_native_units()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-13-67c9a515d85f> in <module>
----> 1 c.get_native_units()

~\Anaconda3\lib\site-packages\yaqc\_client.py in inner(self, *args, **kwargs)
     59                 ba = sig.bind_partial(self, *args, **kwargs)
     60                 ba.apply_defaults()
---> 61                 return self.send(comm, *ba.args[1:], **ba.kwargs)
     62
     63             inner.__signature__ = sig

~\Anaconda3\lib\site-packages\yaqc\_client.py in inner(self, *args, **kwargs)
     26     def inner(self, *args, **kwargs):
     27         try:
---> 28             return fun(self, *args, **kwargs)
     29         except (ConnectionError, struct.error):
     30             self._socket = Socket(self._host, self._port)

~\Anaconda3\lib\site-packages\yaqc\_client.py in send(self, method, *args, **kwargs)
    100             self._id_counter += 1
    101             return self._socket.message(
--> 102                 method, self._protocol["messages"][method], *args, **kwargs
    103             )
    104

~\Anaconda3\lib\site-packages\yaqc\_socket.py in message(self, method_name, method_schema, *args, **kwargs)
     90         error = self._read("boolean")
     91         if error:
---> 92             raise Exception(self._read(["string"]))
     93         # read response
     94         response = self._read(method_schema.get("response", "null"))

Exception: TypeError('must be string')
```

**Comment by ddkohler** [comment]
debug has the following message--tries to encode the NoneType?
```
<7> DEBUG : 2022-11-09T14:44:25-0600 : analyzer : Traceback (most recent call last):
  File "fastavro/_write.pyx", line 129, in fastavro._write.write_utf8
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dan\Anaconda3\envs\newport\lib\site-packages\yaqd_core\_protocol.py", line 76, in process_requests
    fastavro.schemaless_writer(response_out, response_schema, response)
  File "fastavro/_write.pyx", line 786, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 460, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 422, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 131, in fastavro._write.write_utf8
TypeError: must be string

**Comment by ksunden** [comment]
https://github.com/yaq-project/yaqd-newport/blob/main/yaqd_newport/newport-conex-agp.avpr#L191

rerender your avpr and make sure yaq-traits is up to date

**Comment by ksunden** [comment]
Actually, the fix for this is not released in yaq-traits

@untzag or @ddkohler can you rel prep yaq-traits... no reason to be sitting on a bug fix
